export XIM=fcitx
export XIM_PROGRAM=/usr/bin/fcitx
export XIM_ARGS=""
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export QT4_IM_MODULE=fcitx
export DEPENDS="fcitx"
export XMODIFIERS="@im=fcitx"
export PATH=/usr/lib/python-2.7/bin:$PATH
